### ISSUE TITLE
ESP32-IDF version

### ISSUE THREAD

**Issue by ReinierH** [vpcola/esp32internetRadio#1]
Hi, 

I was wondering which version of the IDF SDK you used to build this project. I'm get some compile errors when I try to compile it with V3. 

Regards,

Reinier

**Comment by vpcola** [comment]
the latest one.

**Comment by ReinierH** [comment]
Hm thats weird, I'm receiving the following error when trying to compile:

`/Users/Reinier/Documents/gitprojects/random/esp32internetRadio/components/mdns_task/./mdns_task.c: In function 'mdns_task':
/Users/Reinier/Documents/gitprojects/random/esp32internetRadio/components/mdns_task/./mdns_task.c:28:5: error: unknown type name 'mdns_server_t'
     mdns_server_t * mdns = NULL;`

**Comment by vpcola** [comment]
Oh, they just moved the definition of mdns_server_t to
esp-idf/components/mdns/private_include/mdns_private.h two months ago which
causes yourb error.

You can move this header back into the include folder if you want to fix it.

**Comment by vpcola** [comment]
there a better way of fixing it though, just call mdns_init() without
parameters, that way there woudnt be a need for mdns_server_t. Ill fix it
when I have time.

**Comment by vpcola** [comment]
Fixed. Get the latest from master branch.

**Comment by vpcola** [comment]
I have no time to test it on my esp32 since I have dismantled my setup. But I managed to fix the compilation problems with the latest ESP-IDF (3.0).
